#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "wa5Bn/v6qmyr"
#define LAYER_STATE_8BIT

#define POINTING_DEVICE_HIRES_SCROLL_ENABLE
#define POINTING_DEVICE_HIRES_SCROLL_EXPONENT 0
#define MOUSE_EXTENDED_REPORT
#define WHEEL_EXTENDED_REPORT
#define NAVIGATOR_TRACKBALL_CPI 60
#define NAVIGATOR_SCROLL_DIVIDER 50

#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define AUTO_MOUSE_DEFAULT_LAYER 3
#define AUTO_MOUSE_THRESHOLD 10
#define AUTO_MOUSE_SCROLL_THRESHOLD AUTO_MOUSE_THRESHOLD / NAVIGATOR_SCROLL_DIVIDER
#define RGB_MATRIX_STARTUP_SPD 60

